# Generated by Django 5.2.6 on 2025-10-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainbatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='brainbatch__group_i_62ca05_idx',
        ),
    ]
